# Generated by Django 5.0.4 on 2024-04-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_domain_tag_userchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
